#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Aug 25 11:02:43 2022

@author: wanders7


List of countries, crops, and years to shift
"""

#Shift is -1 for the FAO year relative to the ENSO year 
# (e.g. 2011 harvest corresponds to a 2010/2011 ENSO event, 
#  so FAO shift is -1 b/c ENSO events counted by their developing year)

#NOTE THAT THIS IS PYTHON INDEXING, so 5 = MJJ, 6 = JJA, 7 = JAS, 8 = ASO

ensoShft = {'Maize':
                    {'Argentina':6, 
                     'Brazil':6, 
                     'Uruguay':6,
                     'Paraguay':5,
                     'Peru':7,
                     
                     'Angola':7,
                     'Namibia':7,
                     'Botswana':7,
                     'Madagascar':7,
                     'South Africa':7,
                     'Lesotho':7,
                     'Zimbabwe':7,
                     'Mozambique':7,
                     'Tanzania':7,
                     'Zambia':7,
                     'Malawi':7,
                     
                     'Rwanda':6,
                     'Burundi':6,
                     #'Somalia':6, #We are forecasting for the long rains now to keep things consistent with lags, so no use current year
                     #'Kenya':6,
                     
                     'Laos':7,
                     'Myanmar':5,
                     'Thailand':7,
                     'Vietnam':7,
                     'Cambodia':5,
                     'Indonesia':6},
                    
            'Sorghum':
                    {'Argentina':6, 
                     'Brazil':6, 
                     'Uruguay':6,
                     'Paraguay':5,
                     'Peru':7,
                     'Angola':7,
                     'Namibia':7,
                     'Botswana':7,
                     'Madagascar':7,
                     'South Africa':7,
                     'Lesotho':7,
                     'Zimbabwe':7,
                     'Mozambique':7,
                     'Tanzania':7,
                     'Zambia':7,
                     'Malawi':7,

                     'Rwanda':6,
                     'Burundi':6,
                     #'Somalia':6, #We are forecasting for the long rains now to keep things consistent with lags, so no use current year
                     #'Kenya':6,

                     'Laos':7,
                     'Myanmar':5,
                     'Thailand':7,
                     'Vietnam':7,
                     'Cambodia':5,
                     'Indonesia':6},
                    
            'Soy':
                    {'Argentina':6, 
                     'Brazil':6, 
                     'Uruguay':6,
                     'Paraguay':5,
                     'Peru':7,
                     'Angola':7,
                     'Namibia':7,
                     'Botswana':7,
                     'Madagascar':7,
                     'South Africa':7,
                     'Lesotho':7,
                     'Zimbabwe':7,
                     'Mozambique':7,
                     'Tanzania':7,
                     'Zambia':7,
                     'Malawi':7,

                     'Rwanda':6,
                     'Burundi':6,

                     'Laos':7,
                     'Myanmar':5,
                     'Thailand':7,
                     'Vietnam':7,
                     'Cambodia':5,
                     'Indonesia':6},
            'Rice':
                    {'Indonesia':7,
                     'Brazil':7}, #fewest lags

            'Wheat': 
                    {'Afghanistan':7, 
                     'Albania':7, 
                     'Algeria':7,
                     'Argentina':2, #almost always lag bcause harvest ends in early jan
                     'Armenia':8,
                     'Austria':7, 
                     'Australia':3, #almost always lag bcause harvest ends in early jan
                     'Azerbaijan':8,  
                     'Bangladesh':7, 
                   'Belarus':7, 
                   'Belgium':7, 
                   'Belgium-Luxembourg':7, 
                   'Belize':7, 
                   'Bhutan':7, 
                   'Bosnia and Herzegovina':7,

                   'Bulgaria':7,
                   'Cambodia':7,  

                   'China, Hong Kong SAR':7,
                   'China':7, 
                   'Croatia':7,
                   'Cyprus':7,
                   'Czechia':7,
                   'Czechoslovakia':7,
                   'North Korea':7, 
                   'Denmark':8, 
                   'Egypt':7,  
                   'Estonia':7,

                   'Finland':7,
                   'France':7,
                   'Georgia (cntry)':8, 
                   'Germany':7, 
                   'Greece':7, 
                   'Grenada':7,
                   'Hungary':7, 
                   'Iceland':7, 
                   'India':7, 
                   'Iran':7, 
                   'Iraq':7, 
                   'Ireland':7,
                   'Israel':7,
                   'Italy':7,
                   'Jamaica':7, 
                   'Japan':7,
                   'Jordan':7, 
                   'Kuwait':7, 
                   'Kyrgyzstan':7,
                   
                   'Laos':7,
                   'Latvia':7, 
                   'Lebanon':7,
                   'Libya':7, 
                   'Lithuania':7,
                   'Luxembourg':7,
                   'Malaysia':7,
                   'Maldives':7,
                   'Malta':7, 
                   'Martinique':7, 
                   'Mauritius':7, 
                   'Mexico':7,
                   'Mongolia':7, 
                   'Montenegro':7,
                   'Morocco':7, 
                   'Myanmar':7, 
                   'Nepal':7,
                   'Netherlands':7, 
                   'New Caledonia':7, 
                   'New Zealand':7, 
                   'North Macedonia':7, 
                   'Norway':7, 
                   'Oman':7,
                   'Pakistan':7, 
                   'Palestine':7,
                   'Poland':7, 
                   'Portugal':7, 
                   'Qatar':7, 
                   'South Korea':7, 
                   'Romania':7, 
                   'Russian Federation':7, 
                   'Saint Vincent and the Grenadines':7, 
                   'Samoa':7,
                    'Saudi Arabia':7, 
                    'Serbia and Montenegro':7, 
                    'Seychelles':7, 
                    'Singapore':7,
                    'Slovakia':7,
                    'Slovenia':7, 
                    'Solomon Islands':7,
                   'Sudan':7, 
                   'Spain':7,
                   'Sri Lanka':7,
                   'Suriname':7,
                   'Sweden':7, 
                   'Switzerland':7,
                   'Syria':7, 
                   'Tajikistan':7,
                   'Thailand':7, 
                   'Timor-Leste':7, 
                   'Trinidad and Tobago':7, 
                   'Tunisia':7, 
                   'Türkiye':7, 
                   'Turkmenistan':7,
                   'Ukraine':7, 
                   'United Arab Emirates':7,
                   'United Kingdom':7,
                   'Tanzania':7, 
                   'United States of America':7, 
                   'Former USSR':7, 
                   'Uzbekistan':7,
                   'Vietnam':7, 
                   'Yemen':7, 
                   'Yugoslavia':7}
            }

